### ISSUE TITLE
Have an "Announcement" category on GitHub Discussions

### ISSUE THREAD

**Issue by jviotti** [nodejs/single-executable#38]
Other repos do have that, but I can't find it here. @RaisinTen Is this something you can enable, assuming you have enough permissions? I'd like to use that category to post frequent updates!

**Comment by jviotti** [comment]
Here is an example from another repo:

<img width="371" alt="Screen Shot 2022-09-16 at 09 49 59" src="https://user-images.githubusercontent.com/2192773/190654477-c6617b9f-6f89-4b2a-a8ff-e2b70404f329.png">

**Comment by RaisinTen** [comment]
I'm able to see this option in the discussions categories 👀

**Comment by jviotti** [comment]
Weird. Maybe I do not have enough permissions?

**Comment by ovflowd** [comment]
I'm also able to see it, hence why I was confused.

**Comment by jviotti** [comment]
Now I see it. What the hell :P Did you do something?

**Comment by jviotti** [comment]
@RaisinTen @ovflowd Ah, I do see it if I go to GitHub Discussions, but I cannot create a new post on it. @RaisinTen Can you give me enough permissions to post to the Announcements category? We should probably give every involved member access?

**Comment by RaisinTen** [comment]
I think that would require giving the `Maintain` role to the @nodejs/single-executable team. Any objections/concerns anyone? If not, I'll do it tomorrow.

**Comment by RaisinTen** [comment]
No objections in 24 hours, so I went ahead. Now everyone in the team has the `Maintain` role. @jviotti you should be able to do this now, closing. Feel free to reopen if you face some problems.

**Comment by jviotti** [comment]
Works!
