### ISSUE TITLE
Patch Node.js core to detect and jump to a section with a single JS file

### ISSUE THREAD

**Issue by jviotti** [nodejs/single-executable#47]

**Comment by ovflowd** [comment]
Isn't this what @RaisinTen's initial PR on nodejs/node is about?

**Comment by sheplu** [comment]
Do you have a bit more information about this issue ?  implementation side or final result ?

**Comment by RaisinTen** [comment]
Now that https://github.com/nodejs/node/pull/45038 has landed, I think this can be closed.
