### ISSUE TITLE
Build an SEA CLI MVP

### ISSUE THREAD

**Issue by jviotti** [nodejs/single-executable#49]
Potentially as part of this repository for now. The CLI would do something like:

- Bundle the input package into a single JS file. If that's not possible, error out for now
- Download the correct Node.js binaries from GitHub Releases
- Inject the JS file as a new section using Postject
- Bonus: Provide code-signing support
- Bonus: Provide packaging support

**Comment by sheplu** [comment]
I could work on the CLI part to have something nice but will mostly need help on some part with postject as I don't know it but I can that. I will maybe have some question on the topic

**Comment by RaisinTen** [comment]
@sheplu feel free to ask any questions you have. I'd be happy to help out!

**Comment by tony-go** [comment]
@sheplu you can get inspiration from https://github.com/nodejs/postject/

I'd like to help on that anyway ^^

**Comment by aalmiray** [comment]
FWIW [JReleaser](https://jreleaser.org) is a release tool that can take binaries created by your build tool of choice and release them to GitHub and [supported](https://jreleaser.org/guide/latest/integrations.html) package managers. More information can be found at its documentation page. 

Perhaps it could help with the package manager option listed above.

**Comment by jviotti** [comment]
Closing this as Node.js does it already.
