### ISSUE TITLE
Node.js Single Executable Meeting 2022-10-31

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/single-executable#54]
## Time

Start: **UTC Mon 31-Oct-2022 15:30 (03:30 PM)**
End: **UTC Mon 31-Oct-2022 16:30 (04:30 PM)**

## Agenda

Inclusion of postject in the Node.js binary
* deps: add postject [#45066](https://github.com/nodejs/node/pull/45066)

## Invited

* @nodejs/single-executable

## Joining the meeting

Zoom link: <https://zoom.us/j/97381983106>

**Comment by RaisinTen** [comment]
@mhdawson could you please add this event to http://nodejs.org/calendar, so that everyone who has added that calendar to their own calendars can get notified of this event?

**Comment by mhdawson** [comment]
I've added it now.
