### ISSUE TITLE
Nominating @tony-go

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/single-executable#56]
@tony-go expressed interest in working on the single-executable initiative:
* He attended this meeting - https://github.com/nodejs/single-executable/blob/51e527aaa31730db340e300e6f8d9f681a36f793/meetings/2022-10-31.md
* He also paired up with me to try to unblock postject's development - https://github.com/nodejs/build/pull/3114

So I'd like to nominate him!

If there are no objections / blocking concerns, I'll add him to the single-executable team after 24 hours.

cc @nodejs/single-executable

**Comment by jviotti** [comment]
I'm :+1: on it.

**Comment by sheplu** [comment]
100% supporting that :)

**Comment by RaisinTen** [comment]
24 hours have passed, so I have added @tony-go to the team, closing! 🎉

**Comment by tony-go** [comment]
Thanks ^^

Happy to join 🎉
