### ISSUE TITLE
Leaving SEA team 👋

### ISSUE THREAD

**Issue by ovflowd** [nodejs/single-executable#76]
Hey, folks 👋 I just wanted to mention that I'm leaving the SEA team. Reasons are obvious; I'm extremely busy with existing work with the Next-10 and the Website & Build Teams.

I super appreciate the fantastic work you all are doing here! And I'm genuinely sorry for not being part of the talks since a good time ago, Yet I appreciate any impact/contribution I could make!

Thank you all!

**Comment by RaisinTen** [comment]
Thank you for everything Claudio! ❤️

Looks like you are no longer a member of https://github.com/orgs/nodejs/teams/single-executable, so I'll close this for now.

**Comment by tony-go** [comment]
Thank you @ovflowd for all 🥰

**Comment by ovflowd** [comment]
Yeah! I just didn't want to be a "stale" member, and happy to rejoin at any time :)
