### ISSUE TITLE
mjs is not supported??

### ISSUE THREAD

**Issue by pkit** [nodejs/single-executable#77]
Producing injected library from `*.mjs` file yields this in runtime:
```
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at embedderRunCjs (node:internal/util/embedding:18:27)
    at node:internal/main/embedding:18:8

Node.js v20.5.1
```

**Comment by RIAEvangelist** [comment]
Set the type to module in your package.json

**Comment by pkit** [comment]
That's an output from a bundler, I don't want to set the type to module. It will break everything else.

**Comment by RaisinTen** [comment]
https://github.com/nodejs/node/blob/0409cdd91ca5cabcfffca53e1721437145545469/doc/api/single-executable-applications.md?plain=1#L31-L32:

> The single executable application feature currently only supports running a single embedded script using the [CommonJS](https://nodejs.org/api/modules.html#modules-commonjs-modules) module system.

So ESM is not supported yet. Would it be possible for you to transpile your code to CJS before the injection?

**Comment by pkit** [comment]
Yup, figured. Ok, transpiled to cjs. Looks like it works.
Fails hard on subprocess spawns, but that's expected.
Will close the issue.
