### ISSUE TITLE
Zero-copy access of assets in SEA

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/single-executable#83]
Spinning off from https://github.com/nodejs/node/pull/50960 - currently to be safe the asset returned from that PR are essentially copies:

1. sea.getAsset() with encoding: returns a decode string, which is a copy
2. sea.getAsset(): returns a copy of the asset in an ArrayBuffer
3. sea.getAssetAsBlob(): returns the data as a blob, the data is ultimately still only available as copies via `blob.arraybuffer()` or `blob.text()`

For now, in https://github.com/nodejs/node/pull/50960, the most straightforward way to provide zero-copy access to the asset is just a matter of exposing `sea.getRawAsset()`. I originally intended to expose it but decided to not do that for the PR because there are some risks in returning the raw data to the user directly - if user mutates the data, the process typically would crash with an access violation since the blobs injected by postject are in protected segments at runtime. Since JavaScript does not have an immutable ArrayBufferView yet (only a very early proposal https://github.com/tc39/proposal-limited-arraybuffer) I don't find much we can do to prevent users from mutating the data. However copying can incur a non-trivial overhead depending on the size of the asset. So I am opening an issue to see if there are any other ideas to provide a bit more protection in the API, or if we don't really care about the protection and just want to expose it directly.

cc @nodejs/single-executable

**Comment by mcollina** [comment]
I would just document it.

**Comment by joyeecheung** [comment]
I think patching process.dlopen could be layered on top but if you bundle the addons in it should be possible for you to load them dynamically after putting them on disk one way or another. (This issue is for discussion about the in-memory "copying" of the assets specifically, by the way).

**Comment by joyeecheung** [comment]
I noticed that the reason why `sea.getRawAsset()` crashed was because a) postject injects the section as read-only and b) it may not be aligned. Potentially injecting it with a different tool (?) may not lead to a crash if you modify the loaded section. As far as Node.js core is concerned I think we could just expose the API for getting raw data and document that if users use postject to inject the data, modifying the raw asset is likely to lead to a crash.

**Comment by robertsLando** [comment]
Is this supported now?

**Comment by joyeecheung** [comment]
Yes since https://github.com/nodejs/node/pull/50960 has landed

**Comment by Seblor** [comment]
I'm a bit lost, how can native addons be included now that this is merged ? I cannot find up to date documentation on that subject.
