### ISSUE TITLE
[Question] Difference between blob and pkg solutions

### ISSUE THREAD

**Issue by Drjacky** [nodejs/single-executable#85]
I followed https://nodejs.org/api/single-executable-applications.html but encountered this issue: https://github.com/vercel/pkg/issues/2037 (I know, wrong place to create that ticket!)

but with the `pkg` solution, it works perfectly.
I want to know what are the differences between `pkg` and nodejs-single-executable solutions, for my own understanding?

**Comment by GabenGar** [comment]
Without the code in question it's impossible to tell. `pkg` probably transpiles the code to CJS format (and whatever custom syntax the transpiler allows), while SEA just saves it as is. I am not sure why are you invoking the binaries with `node`, since those outputs are supposed to be standalone.

**Comment by Drjacky** [comment]
Thanks for the reply!
Because one standalone worked and the other didn't work; was wondered what's the difference.
